[package]
name = "aegivue-media"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
axum.workspace = true
chrono.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
aegivue-common = { path = "../aegivue-common" }
