CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE recording_mode AS ENUM ('continuous','motion');
CREATE TYPE stream_kind AS ENUM ('main','sub');
CREATE TYPE event_kind AS ENUM ('motion','object','manual','system');

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, display_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cameras (id varchar(64) PRIMARY KEY CHECK(id ~ '^[a-z0-9][a-z0-9_-]{2,63}$'), name varchar(120) NOT NULL, enabled boolean NOT NULL DEFAULT true, host varchar(253) NOT NULL, port integer NOT NULL DEFAULT 554 CHECK(port BETWEEN 1 AND 65535), username text, password_secret text, main_stream text NOT NULL, sub_stream text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
COMMENT ON COLUMN cameras.password_secret IS 'Credential material; never expose through API views or logs. Encryption-at-rest integration is planned.';
CREATE TABLE recording_configs (camera_id varchar(64) PRIMARY KEY REFERENCES cameras(id) ON DELETE CASCADE, enabled boolean NOT NULL DEFAULT true, mode recording_mode NOT NULL DEFAULT 'continuous', pre_event_seconds integer NOT NULL DEFAULT 5 CHECK(pre_event_seconds BETWEEN 0 AND 120), post_event_seconds integer NOT NULL DEFAULT 15 CHECK(post_event_seconds BETWEEN 0 AND 600));
CREATE TABLE motion_configs (camera_id varchar(64) PRIMARY KEY REFERENCES cameras(id) ON DELETE CASCADE, enabled boolean NOT NULL DEFAULT false, stream stream_kind NOT NULL DEFAULT 'sub', analysis_fps numeric(5,2) NOT NULL DEFAULT 5 CHECK(analysis_fps > 0 AND analysis_fps <= 30), sensitivity numeric(4,3) NOT NULL DEFAULT .65 CHECK(sensitivity BETWEEN 0 AND 1));
CREATE TABLE motion_zones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), camera_id varchar(64) NOT NULL REFERENCES cameras(id) ON DELETE CASCADE, name varchar(120) NOT NULL, enabled boolean NOT NULL DEFAULT true, exclusion boolean NOT NULL DEFAULT false, polygon jsonb NOT NULL, UNIQUE(camera_id,name));
CREATE TABLE events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), camera_id varchar(64) NOT NULL REFERENCES cameras(id) ON DELETE CASCADE, kind event_kind NOT NULL, started_at timestamptz NOT NULL, ended_at timestamptz, score numeric(6,5), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX events_camera_started_idx ON events(camera_id,started_at DESC);
CREATE TABLE recordings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), camera_id varchar(64) NOT NULL REFERENCES cameras(id) ON DELETE RESTRICT, event_id uuid REFERENCES events(id) ON DELETE SET NULL, start_time timestamptz NOT NULL, end_time timestamptz, file_path text NOT NULL UNIQUE, file_size bigint CHECK(file_size >= 0), container varchar(16) NOT NULL, video_codec varchar(32), audio_codec varchar(32), width integer, height integer, fps numeric(7,3), duration_ms bigint, motion_score numeric(6,5), protected boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX recordings_camera_start_idx ON recordings(camera_id,start_time DESC);
CREATE TABLE recording_segments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), recording_id uuid NOT NULL REFERENCES recordings(id) ON DELETE CASCADE, sequence integer NOT NULL CHECK(sequence >= 0), file_path text NOT NULL UNIQUE, start_time timestamptz NOT NULL, end_time timestamptz, file_size bigint CHECK(file_size >= 0), UNIQUE(recording_id,sequence));
CREATE TABLE event_objects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE, label varchar(100) NOT NULL, confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1), box jsonb NOT NULL, detector varchar(120) NOT NULL);
CREATE TABLE alert_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(120) NOT NULL, enabled boolean NOT NULL DEFAULT true, event_kind event_kind, camera_id varchar(64) REFERENCES cameras(id) ON DELETE CASCADE, destination_type varchar(32) NOT NULL, destination_config jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE alert_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rule_id uuid NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE, event_id uuid REFERENCES events(id) ON DELETE SET NULL, status varchar(24) NOT NULL, attempted_at timestamptz NOT NULL DEFAULT now(), error_message text);
CREATE TABLE system_settings (key varchar(120) PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());

CREATE VIEW camera_views AS SELECT c.id,c.name,c.enabled,c.host,c.port,c.username,c.main_stream,c.sub_stream,r.enabled recording_enabled,r.mode recording_mode,r.pre_event_seconds,r.post_event_seconds,m.enabled motion_enabled,m.stream motion_stream,m.analysis_fps,m.sensitivity,c.created_at,c.updated_at FROM cameras c JOIN recording_configs r ON r.camera_id=c.id JOIN motion_configs m ON m.camera_id=c.id;
